### PR TITLE
Setup for Rebuildable images

### PR DESCRIPTION
**Pull request by cevich**
Currently, container images are point-in-time builds.  Whatever happens to be present in the package repositories at build-time is content included in the images.  This is undesirable from a user perspective as it results in the image contents frequently changing. It's also undesirable from an operational perspective as there is no way to recover a prior image should it become corrupt or get pruned from the registry server.

This PR puts the machinery in place to support rebuildable "stable" container images.  This PR does not include the automation necessary to maintain the static package lists.  A future PR may add that functionality, for now they're simply re-generated for every CI run.

### CODE REVIEW

**Comment by cevich** [comment]
@edsantiago when you get a chance, would you mind giving `maintain_packages.sh` and the `Containerfile` changes a quick once-over?  This PR is still a WIP, but I don't want to carry onward, if you feel any major changes are needed.  TIA.

**Comment by cevich** [comment]
Force-push: New VM image, increased timeouts, removed `dnf install unzip` workaround.

**Comment by cevich** [comment]
Force-push: New CI VM image.  Added distro name/release to metadata.

**Comment by cevich** [comment]
Force-push: Disabled arm testing (in DO NOT MERGE commit) because the Fedora repos are misbehaving.

**Comment by cevich** [comment]
Heavily considering abandoning this effort, it seems to be taking up a LOT of time and adding a lot of complexity.  I'm currently facing a problem that only reproduces in CI and not locally (using same version of podman).  Also, basically nobody (IMHO) worries about point-in-time rebuildable container images, why should we be different?

**Comment by edsantiago** [comment]
I've been reviewing and re-reviewing, usually in one-to-two-hour chunks. The general idea SGTM but this is huge and complicated. I will pause review until you decide whether to proceed with it.

**Comment by cevich** [comment]
> I will pause review until you decide whether to proceed with it.

Thanks, and thanks for taking the time to look.  It is big and not even the end of it, more work is needed to get Renovate or some other tool to actually update the static files - otherwise there's no point and it's only extra complexity for nothing.

I'm leaning more toward abandoning it every time it crosses my mind.  The fact I can't get CI to pass (but it works locally) is also weighing on me heavily.

**Comment by cevich** [comment]
I'm going to abandon this, it's too complex and "against the grain" WRT how other images are built.  Better to spend my time on more useful items rather than spin my wheels any further here.

**Pull request closed without merging**
